version: "3.8"
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - mongodb
      - db
    image: 'nitesh18400/bdmh_assignment_1'
  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  mongodb:
      container_name: mongodb
      image: mongo
      ports:
        - 27017:27017
      logging:
        driver: none
  